src/definitions/variable.rs
Sometimes the span of a variable starts on the line before the type name, so miette would show arrows instead of underline.
=> fix(variable): highlighted span

src/files.rs
This makes it so that a project can have a `.nsignore` file at the root and pass `src` as a path to scan. Otherwise any ignore file above `src` is ignored.
=> fix: parent ignore files must be enabled

flake.lock, src/definitions/constructor.rs, src/definitions/enumeration.rs, src/definitions/error.rs, src/definitions/event.rs, src/definitions/function.rs, src/definitions/mod.rs, src/definitions/modifier.rs, src/definitions/structure.rs, src/definitions/variable.rs
The macro was required when it was being called in a loop to have the `continue` statement. But now that it returns an error, we can simply use a normal function.
=> refactor(definitions): replace macro with function

.env.example, .lintspec.toml, README.md, src/config.rs, src/definitions/constructor.rs, src/definitions/mod.rs, src/definitions/structure.rs
The default behavior has changed. Whereas before, struct members had to be documented with `@param`, this is now optional and controlled with the new `--struct-params` argument.
=> feat(cli)!: make documenting struct members optional

src/definitions/mod.rs
Due to the question mark quantifier in some queries, I was getting duplicate returns (one with returns and one without for functions, for example). I now deduplicate those by looking at the span.
=> fix(definitions): duplicate results for queries with quantifiers

src/definitions/mod.rs, test-data/ParserTest.sol
According to the rules implemented by solc, the only comments that constitute NatSpec are:
- The last multiline doc-comment before a definition
- The block of last contiguous single-line doc-comments before a definition
```solidity
/// @dev This should be ignored
/**
* @dev This should be ignored
*/
/// @notice  This is NatSpec
/// @param a This is NatSpec
function foo(uint256 a) internal { }
/// @dev This should be ignored
/// @notice  This is NatSpec
/// @param a This is NatSpec
function foo(uint256 a) internal { }
/**
* @dev This should be ignored
*/
/**
* @notice This is NatSpec
* @param a This is NatSpec
*/
function foo(uint256 a) internal { }
```
=> fix(definitions): comments filtering

src/natspec.rs
=> feat(natspec): parser improvements to support weird edge-cases

Cargo.lock, Cargo.toml, src/definitions/constructor.rs, src/definitions/enumeration.rs, src/definitions/error.rs, src/definitions/event.rs, src/definitions/function.rs, src/definitions/mod.rs, src/definitions/modifier.rs, src/definitions/structure.rs, src/definitions/variable.rs
`as_...()` were renamed to `to_...()` because they consume the input. Added `as_...()` that takes in a reference and returns a reference.
=> refactor(definitions)!: conversion functions

Cargo.toml
SIMD is done automatically in `ignore`, feature is a no-op.
=> chore: remove useless feature

README.md
It's probably better if people depend on a fixed version of the action.
=> docs: pin action version in readme

.lintspec.toml, README.md, src/config.rs, src/lint.rs, src/main.rs, src/parser/mod.rs, src/parser/slang.rs, src/utils.rs, test-data/UnsupportedVersion.sol, tests/tests-basic-sample.rs, tests/tests-interface-sample.rs, tests/tests-library-sample.rs, tests/tests-parser-test.rs
This PR adds the option to skip the solidity version detection from pragma statements. This would be useful for users who would like to use a `lintspec` version where the `slang_solidity` dependency does not support a given (probably newer) Solidity version. For example, the latest `slang_solidity` version does not support Solidity 0.8.29 at the time of writing. Projects which use that Solidity version but not any of the new syntax it adds could very well use the 0.8.28 version of the parser as an escape hatch until the new version is officially supported by `slang_solidity`.
- The `lint:lint` function now takes a parser instance instead of a generic type.
- The `parser::Parse` trait's `parse_document` function now takes `&mut self` to enable configurable and/or stateful parsers.
=> feat!: allow to skip solidity version detection

flake.lock, src/definitions/constructor.rs, src/definitions/enumeration.rs, src/definitions/error.rs, src/definitions/event.rs, src/definitions/function.rs, src/definitions/mod.rs, src/definitions/modifier.rs, src/definitions/structure.rs, src/definitions/variable.rs, src/error.rs, src/lint.rs, src/parser/slang.rs, src/utils.rs
This way, `slang_solidity` does not have to be a hard dependency of this crate later on.
=> refactor(definitions): create own text range type

flake.lock, src/lint.rs, src/parser/mod.rs, src/parser/slang.rs
This PR changes the signature of the `Parse::parse_document` function so that it accepts a `impl io::Read` reader. This makes the API more versatile and allows to read from streams, stdin, etc.
- `Parse::parse_document ` now takes an `impl io::Read` instead of an `impl AsRef<Path>`.
Closes #73
=> refactor(parser)!: change input from path to reader

src/parser/slang.rs, tests/snapshots/tests_parser_test__basic.snap, tests/snapshots/tests_parser_test__constructor.snap, tests/snapshots/tests_parser_test__enum.snap, tests/snapshots/tests_parser_test__inheritdoc.snap, tests/snapshots/tests_parser_test__struct.snap
Fixing an edge case where the location of the `TextRange` for an item (in compact mode) would start at a normal (non-natspec) comment.
=> fix(slang): ignore non-doc-comments in span

src/parser/slang.rs, test-data/ParserTest.sol, tests/snapshots/tests_parser_test__basic.snap, tests/snapshots/tests_parser_test__constructor.snap, tests/snapshots/tests_parser_test__enum.snap, tests/snapshots/tests_parser_test__inheritdoc.snap, tests/snapshots/tests_parser_test__struct.snap
https://github.com/beeb/lintspec/pull/77 made the parser throw an error if it encounters NatSpec comments starting with `////` or `/***`, which is fine, but this error should not propagate to the end user.
These comments are now considered as normal comments and not NatSpec comments, so they get skipped completely when checking NatSpec, which is in line with what solc does.
=> fix(slang): ignore natspec comments which start with too many slashes or stars

src/parser/slang.rs, test-data/Fuzzers.sol, tests/snapshots/tests_fuzzers__fuzzers.snap, tests/tests-fuzzers.rs
The CST had an EndOfLine inside of the first non-trivia node for some variable declarations. This resulted in a wrong line number on the span.
=> fix(slang): span start for variable definition with non-native type

Cargo.lock, Cargo.toml, src/definitions/structure.rs, src/lint.rs
Although the solidity compiler generates warning for "ophan" `@param` natspec entries in function-like items, it doesn't do it for structs and enums (because it's not part of the spec, at least yet). 
Lintspec will now report extraneous `@param` entries for all items.
=> feat(lint): orphan params generate diagnostics

README.md, src/config.rs, src/definitions/function.rs, src/definitions/modifier.rs, src/lint.rs, test-data/BasicSample.sol, tests/snapshots/tests_basic_sample__all.snap, tests/snapshots/tests_basic_sample__all_no_inheritdoc.snap, tests/snapshots/tests_basic_sample__basic.snap, tests/snapshots/tests_basic_sample__constructor.snap, tests/snapshots/tests_basic_sample__enum.snap, tests/snapshots/tests_basic_sample__inheritdoc.snap, tests/snapshots/tests_basic_sample__struct.snap, tests/tests-basic-sample.rs
Because the default value for this item is `false`, this changes the behavior compared to previous versions (because it used the `inheritdoc` flag which defaults to `true`) and is a breaking change.
To restore the v0.7 behavior, set `inheritdoc_override = true` in the config file under the `[lintspec]` section.
Closes https://github.com/beeb/lintspec/issues/123
=> feat!: add `inheritdoc_override` param for internal functions and modifiers

Cargo.lock, Cargo.toml, benches/lint.rs, benches/parser.rs, src/error.rs, src/lib.rs, src/lint.rs, src/main.rs, src/parser.rs, src/parser/slang.rs, src/parser/solar.rs, tests/common.rs, tests/tests-solar.rs
This PR changes the behavior of parsers to be stateful and keep references to the source code buffers until the end of parsing. The client can then retrieve the sources' contents while destroying the last parser instance with `Parse::get_sources`.
This allows to make the `SolarParser` stateful and re-use the same session, while avoiding to clone the source buffers for pretty diagnostics. Performance is improved.
Closes https://github.com/beeb/lintspec/issues/126
=> feat(parser)!: parsers own the source buffers

.github/workflows/release.yml, dist-workspace.toml, flake.lock, flake.nix, rust-toolchain.toml
GitHub Actions will [stop supporting the free Intel macOS workers](https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down) soon and Rust also [demoted that target to Tier 2](https://blog.rust-lang.org/2025/09/18/Rust-1.90.0/#demoting-x86-64-apple-darwin-to-tier-2-with-host-tools).
=> build: remove mac x86 target
